asdf

diff --git a/.github/workflows/deploy_ethorian_sites.yml b/.github/workflows/deploy_ethorian_sites.yml
--- a/.github/workflows/deploy_ethorian_sites.yml
+++ b/.github/workflows/deploy_ethorian_sites.yml
@@ -218,38 +218,38 @@ jobs:
             echo "Failure: Log entry not found within 10 minutes."
           fi
       
-  check_sites:
-    needs: [plan, taint, deploy, dns, check_log_entry]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check if Site is Ready
-        run: |
-          # Wait for site to be ready with a 10-minute timeout
-          end_time=$((SECONDS+600))  # 600 seconds (10 minutes) timeout for site check
-          while [[ $SECONDS -lt $end_time ]]; do
-            if curl --head --fail http://ethorian.net; then
-              echo "Site is responding"
-              exit 0  # Success
-            fi
-            echo "Site is not responding, waiting..."
-            sleep 10  # Wait for 10 seconds before retrying
-          done
-          echo "Site did not respond within the timeout"
-          exit 1  # Timeout
+  # check_sites:
+  #   needs: [plan, taint, deploy, dns, check_log_entry]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check if Site is Ready
+  #       run: |
+  #         # Wait for site to be ready with a 10-minute timeout
+  #         end_time=$((SECONDS+600))  # 600 seconds (10 minutes) timeout for site check
+  #         while [[ $SECONDS -lt $end_time ]]; do
+  #           if curl --head --fail http://ethorian.net; then
+  #             echo "Site is responding"
+  #             exit 0  # Success
+  #           fi
+  #           echo "Site is not responding, waiting..."
+  #           sleep 10  # Wait for 10 seconds before retrying
+  #         done
+  #         echo "Site did not respond within the timeout"
+  #         exit 1  # Timeout
         
-      - name: Check if Auth Site is Ready
-        run: |
-          # Use curl to make a request without authentication
-          response=$(curl -s -I -u username:password http://ethorian.net:8081)
+  #     - name: Check if Auth Site is Ready
+  #       run: |
+  #         # Use curl to make a request without authentication
+  #         response=$(curl -s -I -u username:password http://ethorian.net:8081)
 
-          # Check if the response contains "HTTP/1.1 401 Unauthorized"
-          if [[ $response == *"HTTP/1.1 401 Unauthorized"* ]]; then
-            echo "Authentication required. Site is protected."
-            exit 0  # Exit with success
-          else
-            echo "Authentication not required. Site is not protected or accessible."
-            exit 1  # Exit with failure
-          fi
+  #         # Check if the response contains "HTTP/1.1 401 Unauthorized"
+  #         if [[ $response == *"HTTP/1.1 401 Unauthorized"* ]]; then
+  #           echo "Authentication required. Site is protected."
+  #           exit 0  # Exit with success
+  #         else
+  #           echo "Authentication not required. Site is not protected or accessible."
+  #           exit 1  # Exit with failure
+  #         fi
 
   # notify:
   #   needs: [plan, taint, deploy, dns, check_log_entry, check_sites]
