check for site job in gha

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -155,3 +155,28 @@ jobs:
       run: |
         terraform apply -auto-approve
         echo "instance_public_ip=$(terraform output instance_public_ip)"
+
+  # check_site:
+  #   needs: dns
+  #   if: github.event.inputs.apply == 'true'
+    
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 10  # Set the maximum runtime for this job
+
+  #   steps:
+  #   - name: Checkout repository
+  #     uses: actions/checkout@v2
+
+  #   - name: Wait for Site to Be Ready
+  #     run: |
+  #       end_time=$((SECONDS+600))  # 600 seconds (10 minutes) timeout
+  #       while [[ $SECONDS -lt $end_time ]]; do
+  #         if curl --head --fail https://ethorian.net; then
+  #           echo "Site is responding"
+  #           exit 0  # Success
+  #         fi
+  #         echo "Site is not responding, waiting..."
+  #         sleep 10  # Wait for 10 seconds before retrying
+  #       done
+  #       echo "Site did not respond within the timeout"
+  #       exit 1  # Timeout
